---
   - name: install packages
     yum:
       name:
         - docker
         - git
         - httpd
         - tree
   - name: start docker
     yum:
       name:
         - docker
       enabled: yes
