---
- hosts: praveen4
  strategy: free
  become: true
  gather_facts: true
  tasks:
    - name: yum and services
      yum:
        name: httpd
        state: absent
    - name: start the services
      service:
        name: httpd
        state: stopped
        
        
